### ISSUE TITLE
Messages from Telegram do not get saved to Mongo DB

### ISSUE THREAD

**Issue by IlliaSitkov** [kmaooad/caja22-supraaa#1]
Messages from Telegram which are sent to the deployed azure function do not get saved to Mongo DB. When the function is tested locally with Postman messages do get saved. When trying to POST a message to the deployed function, a 401 Not Authorized error occurs.
![Знімок екрана 2022-10-11 о 10 40 48](https://user-images.githubusercontent.com/65659336/195025989-35fdfb9a-d803-4c73-a9e6-33877e809a24.png)

**Comment by ironpercival** [comment]
https://stackoverflow.com/questions/62320289/failed-to-import-the-uri-unable-to-look-up-txt-record-for-host-cluster0-ohzuo-m
